### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AmirNaghibi**

### CODE REVIEW

**Comment by bfbachmann** [comment]
@AmirNaghibi Did you delete the PR template?

**Comment by AmirNaghibi** [comment]
Yes. Because it was a simple grammar check. There is a conflict with a tutorial link. I just resolved the conflict. Should be fine now

**Comment by AmirNaghibi** [comment]
Is it failing b/c I deleted the template?

**Comment by bfbachmann** [comment]
@AmirNaghibi In the future, please don't delete the PR template. The whole reason it's there is to prompt people to explain their changes. It's no use if you just delete it anyway.

**Pull request merged**
